waypoints:
  - [0.0, 0.0, 0.7]  # 第一组起点
  - [1.0, 0.0, 0.7]  # 第一组终点
  - [1.0, 0.0, 0.7]  # 第二组起点
  - [2.0, 0.0, 0.7]  # 第二组终点
  - [2.0, 0.0, 0.7]  # 第三组起点
  - [3.0, 0.0, 0.7]  # 第三组终点

# 其他配置保持不变
arrival_threshold: 1.0  # 到达阈值（米） 