#############################################
#   Mapping                                 #
#############################################

rog_map:
  resolution: 0.3
  inflation_resolution: 0.4
  inflation_step: 1
  unk_inflation_en: false 
  unk_inflation_step: 1
  map_size: [60,60,10] 
  fix_map_origin: [0,0,0] 
  frontier_extraction_en: true

  virtual_ceil_height: 9999 
  virtual_ground_height: -9999 

  load_pcd_en: false 
  map_sliding: 
    enable: false
    threshold: 0.3

  esdf:
    enable: true
    resolution: 0.4
    local_update_box: [60,60,10] 

  ros_callback:
    enable: true
    cloud_topic: "/cloud_registered"
    odom_topic: "/Odometry"
    odom_timeout: 3.0

  visualization:
    enable: true
    use_dynamic_reconfigure: false
    time_rate: 10
    frame_rate: 0
    range: [100,100,10] 
    frame_id: "world"
    pub_unknown_map_en: false

  intensity_thresh: -10
  point_filt_num: 10 

  raycasting:
    enable: true
    batch_update_size: 1
    local_update_box: [60,60,10] 
    ray_range: [0.0, 5] 
    p_min: 0.12
    p_miss: 0.49
    p_free: 0.499
    p_occ: 0.85
    p_hit: 0.9
    p_max: 0.98
    unk_thresh: 1.0
